[package]
name = "rust-google-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
reqwest = { version = "0.11.22", features = ["blocking"] }
tl = "0.7.7"
