name: Docker publish

on:
  push:
    branches: [ master ]
    tags: [ v* ]

jobs:
  docker-publish:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker build with latest
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .;

      - name: Docker build with tag
        if: contains(github.ref_name, 'v*')
        run: docker build -t ${{ secrets.DOCKER_REPO }}:${{github.ref_name}} .;

      - name: Login into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push image:latest to docker hub
        run: docker push ${{ secrets.DOCKER_REPO }}:latest

      - name: Push image:tag to docker hub
        if: contains(github.ref_name, 'v*')
        run: docker push ${{ secrets.DOCKER_REPO }}:latest
